version: 2
jobs:
  build:
    docker:
      - image: jandrey15/cci-demo-docker-primary:0.0.1

    working_directory: ~/app

    # branches:
    #   ignore:
    #     - develop
    #     - /feature-.*/

    # branches:
    #   only:
    #     - master
    #     - /rc-.*/

    steps:
     - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test
          
  deploy-stage:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/app  
    steps:
      - checkout
      - run:
          name: Deployment
          command: sh deployments/qa.sh        
          
  deploy-prod:
    machine:
      enabled: true
    working_directory: /tmp/app  
    steps:
      - checkout
      - run:
          name: Deployment
          command: sh deployments/qa.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: stage
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master    
      